name: cas-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: install gtest manually
      run: sudo apt-get install doxygen libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: make
      run: cd build && doxygen -v && make tst docs
    - name: Run Test
      run: build/tst/tst
    - name: Build HTML docs
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working-directory: 'docs/'
